### ISSUE TITLE
 python ../run_ped_sim.py -t load_founders -n test_fam.nx -v load_founders/lwk_1kg_toydata.vcf -o testfam_load

### ISSUE THREAD

**Issue by goodcqzz** [MiguelGuardado/py_ped_sim#8]
ERROR (Genome_Class::ExecuteMethod_readFromVCF): VCF file AA value must be A/C/G/T.

Error on script line 87, character 12:

   p1.genomes.readFromVCF(exp_founder_vcf_filepath, m1);
              ^^^^^^^^^^^

**Comment by MiguelGuardado** [comment]
This error is caused by having your inputted vcf file contain non-biallelic SNPs. This is a requirement by SLiM to perform genomic simulations on fixed pedigree structures. Please see our `filter_vcf` feature on how to correct the vcf file to be readable by SLiM.

Thank you for using the software; sorry for the delay in responding to your issue.
